### ISSUE TITLE
Coveralls support broken

### ISSUE THREAD

**Issue by danielyinanc** [Ericsson/eiffel-remrem-generate#9]
XML is generated out of test runs but coveralls upload or some such is not going as planned with integration testing suite.

**Comment by danielyinanc** [comment]
https://travis-ci.org/Ericsson/eiffel-remrem-generate/builds/134782284

At the bottom gradle coveralls task runs and produces no report xml output.

**Comment by vitalca** [comment]
Fixed: https://github.com/Ericsson/eiffel-remrem-generate/commit/203952e6649330dd1f8b5fd3fb2ab93b7a3025cc
